title: Elizabeth C. Delmelle # your name (or website title) here
logo: "/images/ECDelmelle.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an Associate Professor in the Department of City and Regional Planning at the University of Pennsylvania
  and serve as the Director of the Master of Urban Spatial Analytics Program (MUSA)
  <br><br>
  
  <br><br>
  <a href="https://www.linkedin.com/in/elizabeth-delmelle-27a00220a/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://scholar.google.com/citations?user=BjewFecAAAAJ&hl=en">View My Google Scholar Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 4329287150 # your Google Analytics tracking ID here
